baseurl = "https://blog-simple0.netlify.app/"
title = "Simple Hugo Blog"
author = "@sanqitang"
copyright = "Copyright © 2018-2022, @Sanqitang"
canonifyurls = true
paginate = 3

theme = "jeffprod"

[taxonomies]
    tag = "tags"
    archive = "archives"
    
[[menu.main]]
 weight = 6
 identifier = "login"
 name = "Login"
 pre = "<i class=\"sidebar-button-icon fa fa-lg fa-lock\"></i>"
 url = "/login"